import CtyptoTable from "@/components/ CryptoTable";
import {
  Divider,
  FormControl,
  MenuItem,
  Select,
  Stack,
  Typography,
} from "@mui/material";
import Button from "@mui/material/Button";
import axios from "axios";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

const categories = [
  {
    id: "memes",
    label: "Memes",
  },
  {
    id: "solana-ecosystem",
    label: "Solana Ecosystem",
  },
  {
    id: "gaming",
    label: "Gaming",
  },
  {
    id: "ai-big-data",
    label: "AI",
  },
];

export default function Home() {
  const [data, setdata] = useState<any>();
  useEffect(() => {
    (async () => {
      const s = await axios("/api/market", {
        params: {
          limit: 5,
          tagSlugs: "memes", // solana-ecosystem gaming ai-big-data
        },
      });
      setdata(s.data.data);
    })();
  }, []);
  const [open, setOpen] = useState(false);

  const handleDrawerOpen = () => {
    setOpen(true);
  };

  const handleDrawerClose = () => {
    setOpen(false);
  };
  const handleViewDetail = () => {
    handleDrawerOpen();
  };
  return (
    <>
      <Head>
        <title>Tiny Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={`${inter.className}`}>
        <Stack
          sx={{
            textAlign: "center",
            margin: "64px 0",
          }}
          direction="row"
          alignItems="baseline"
          spacing={1}
          justifyContent="center"
        >
          <img src="/logo.png" width={116} />
          <img src="/logo.svg" />
        </Stack>
        <Stack direction="column" className="screen">
          <Stack direction={"row"} spacing={1} justifyContent="space-between">
            <Stack direction="row" spacing={1}>
              <Button variant="outlined">Cryptocurrencies</Button>
              <Divider orientation="vertical" variant="middle" flexItem />
              {categories.map((x) => (
                <Button color="secondary" key={x.id} variant="text">
                  🔥 {x.label}
                </Button>
              ))}
            </Stack>

            <Stack direction={"row"} spacing={1} alignItems={"center"}>
              <Typography
                variant="subtitle2"
                color={"#cfd6e4"}
                sx={{
                  whiteSpace: "nowrap",
                }}
              >
                Show rows
              </Typography>
              <FormControl fullWidth>
                <Select
                  labelId="demo-simple-select-label"
                  id="demo-simple-select"
                  autoWidth
                  // value={age}
                  // label="Age"
                  // onChange={handleChange}
                  size="small"
                  defaultValue={50}
                >
                  <MenuItem value={20}>20</MenuItem>
                  <MenuItem value={50}>50</MenuItem>
                  <MenuItem value={100}>100</MenuItem>
                </Select>
              </FormControl>
            </Stack>
          </Stack>
          <CtyptoTable
            rows={data?.cryptoCurrencyList || []}
            total={data?.totalCount}
            handleViewDetail={handleViewDetail}
          />
        </Stack>
      </main>
    </>
  );
}
